#!/bin/bash
#LAMP stack setup on Arch Linux

#TODO: selection, detection dependencies(curl)

#----Install Apache----
read -p "Do You want to install Apache Web Server? " -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
    #Upadte packages
    sudo pacman -Syu
    #Install Apache HTTP server
    sudo pacman -S apache
    echo -e "\nEdit /etc/httpd/conf.httpd.conf and uncomment unique_id_module.\n"
    read -rsp $'Press any key to continue...\n' -n1 key
    echo -e "\nRestarting httpd...\n"
    sudo systemctl restart httpd
    echo -e "\nEdit /etc/hosts file for adding aditional hostnames.\n"
    read -rsp $'Press any key to continue...\n' -n1 key
    echo -e "\nFeel free to add your web pages to /srv/http/ now!\n"
fi
#--------

#----Install Mysql----
read -p "Do You want to install Mysql Database? " -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
    sudo pacman -S mysql
    echo -e "\nStarting mysqld...\n"
    sudo systemctl start mysqld
    sudo mysql_secure_installation
fi
#--------

#----Install PHP----
read -p "Do You want to install PHP5? " -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
    sudo pacman -S php php-apache
    echo -e "\nAdd these lines to httpd.conf for php support:\n"
    echo -e "\n# Use for PHP 5.x:\n"
    echo -e "\nLoadModule php5_module       modules/libphp5.so\n"
    echo -e "\nAddHandler php5-script php\n"
    echo -e "\nInclude conf/extra/php5_module.conf\n"
    read -rsp $'Press any key to continue...\n' -n1 key
fi
#--------

#Restart apache server
echo -e "\nRestarting Apache HTTP Server for some changes to take effect.\n"
sudo systemctl restart httpd

#----Enable LAMP----
read -p "Do You want to enable LAMP services on startup? " -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
    sudo systemctl enable httpd mysqld
fi
